FROM debian:buster-slim

RUN set -x \
	&& apt update \
	&& apt upgrade -y \
	&& apt install --no-install-recommends --no-install-suggests -y \
	    bash-completion \
		bind9 \
		dnsutils \
		iputils-ping \
	&& apt purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $fetchDeps \
	&& rm -r /var/lib/apt/lists/* \
	&& mkdir /var/log/named \
	&& chown bind:bind /var/log/named \
	&& chmod 0755 /var/log/named

EXPOSE 53

COPY entrypoint-debian-ubuntu-auto.sh /
RUN chmod 777 /entrypoint-debian-ubuntu-auto.sh

ENTRYPOINT ["/entrypoint-debian-ubuntu-auto.sh"]
