version: '3.8'

services:
  bind-alpine-manual:
    build:
      context: .
      dockerfile: Dockerfile-alpine-manual
    image: bind:alpine-manual
    container_name: bind-alpine-manual
    hostname: bind-alpine-manual
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./bind/named.conf:/etc/bind/named.conf
      - ./bind/named.conf.options:/etc/bind/named.conf.options
      - ./bind/named.conf.local:/etc/bind/named.conf.local
      - ./bind/zone:/etc/bind/zone
